
package vaulsys.webservice.nayapaybankservice;

import vaulsys.webservice.walletcardmgmtwebservice.entity.WalletCMSWsEntity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://nayapaybankservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceinquiryotp", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Balanceinquiryotp")
    @ResponseWrapper(localName = "balanceinquiryotpResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.BalanceinquiryotpResponse")
    @Action(input = "http://nayapaybankservice/WebService/balanceinquiryotpRequest", output = "http://nayapaybankservice/WebService/balanceinquiryotpResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/balanceinquiryotp/Fault/Exception")
    })
    public WalletCMSWsEntity balanceinquiryotp(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createwalletlevelone", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Createwalletlevelone")
    @ResponseWrapper(localName = "createwalletleveloneResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.CreatewalletleveloneResponse")
    @Action(input = "http://nayapaybankservice/WebService/createwalletleveloneRequest", output = "http://nayapaybankservice/WebService/createwalletleveloneResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/createwalletlevelone/Fault/Exception")
    })
    public WalletCMSWsEntity createwalletlevelone(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createwalletlevelzero", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Createwalletlevelzero")
    @ResponseWrapper(localName = "createwalletlevelzeroResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.CreatewalletlevelzeroResponse")
    @Action(input = "http://nayapaybankservice/WebService/createwalletlevelzeroRequest", output = "http://nayapaybankservice/WebService/createwalletlevelzeroResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/createwalletlevelzero/Fault/Exception")
    })
    public WalletCMSWsEntity createwalletlevelzero(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayhello", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Sayhello")
    @ResponseWrapper(localName = "sayhelloResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.SayhelloResponse")
    @Action(input = "http://nayapaybankservice/WebService/sayhelloRequest", output = "http://nayapaybankservice/WebService/sayhelloResponse")
    public String sayhello(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "demographicsupdate", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Demographicsupdate")
    @ResponseWrapper(localName = "demographicsupdateResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.DemographicsupdateResponse")
    @Action(input = "http://nayapaybankservice/WebService/demographicsupdateRequest", output = "http://nayapaybankservice/WebService/demographicsupdateResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/demographicsupdate/Fault/Exception")
    })
    public WalletCMSWsEntity demographicsupdate(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atmtransactionlog", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Atmtransactionlog")
    @ResponseWrapper(localName = "atmtransactionlogResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.AtmtransactionlogResponse")
    @Action(input = "http://nayapaybankservice/WebService/atmtransactionlogRequest", output = "http://nayapaybankservice/WebService/atmtransactionlogResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/atmtransactionlog/Fault/Exception")
    })
    public WalletCMSWsEntity atmtransactionlog(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unloadenvelope", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Unloadenvelope")
    @ResponseWrapper(localName = "unloadenvelopeResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.UnloadenvelopeResponse")
    @Action(input = "http://nayapaybankservice/WebService/unloadenvelopeRequest", output = "http://nayapaybankservice/WebService/unloadenvelopeResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/unloadenvelope/Fault/Exception")
    })
    public WalletCMSWsEntity unloadenvelope(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "debitcardrequest", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Debitcardrequest")
    @ResponseWrapper(localName = "debitcardrequestResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.DebitcardrequestResponse")
    @Action(input = "http://nayapaybankservice/WebService/debitcardrequestRequest", output = "http://nayapaybankservice/WebService/debitcardrequestResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/debitcardrequest/Fault/Exception")
    })
    public WalletCMSWsEntity debitcardrequest(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.PingResponse")
    @Action(input = "http://nayapaybankservice/WebService/pingRequest", output = "http://nayapaybankservice/WebService/pingResponse")
    public String ping();

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountlinkotp", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Accountlinkotp")
    @ResponseWrapper(localName = "accountlinkotpResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.AccountlinkotpResponse")
    @Action(input = "http://nayapaybankservice/WebService/accountlinkotpRequest", output = "http://nayapaybankservice/WebService/accountlinkotpResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/accountlinkotp/Fault/Exception")
    })
    public WalletCMSWsEntity accountlinkotp(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ministatement", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Ministatement")
    @ResponseWrapper(localName = "ministatementResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.MinistatementResponse")
    @Action(input = "http://nayapaybankservice/WebService/ministatementRequest", output = "http://nayapaybankservice/WebService/ministatementResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/ministatement/Fault/Exception")
    })
    public WalletCMSWsEntity ministatement(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payment", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.PaymentResponse")
    @Action(input = "http://nayapaybankservice/WebService/paymentRequest", output = "http://nayapaybankservice/WebService/paymentResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/payment/Fault/Exception")
    })
    public WalletCMSWsEntity payment(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadenvelope", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Loadenvelope")
    @ResponseWrapper(localName = "loadenvelopeResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.LoadenvelopeResponse")
    @Action(input = "http://nayapaybankservice/WebService/loadenvelopeRequest", output = "http://nayapaybankservice/WebService/loadenvelopeResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/loadenvelope/Fault/Exception")
    })
    public WalletCMSWsEntity loadenvelope(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unloadwallet", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Unloadwallet")
    @ResponseWrapper(localName = "unloadwalletResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.UnloadwalletResponse")
    @Action(input = "http://nayapaybankservice/WebService/unloadwalletRequest", output = "http://nayapaybankservice/WebService/unloadwalletResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/unloadwallet/Fault/Exception")
    })
    public WalletCMSWsEntity unloadwallet(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmotp", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Confirmotp")
    @ResponseWrapper(localName = "confirmotpResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.ConfirmotpResponse")
    @Action(input = "http://nayapaybankservice/WebService/confirmotpRequest", output = "http://nayapaybankservice/WebService/confirmotpResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/confirmotp/Fault/Exception")
    })
    public WalletCMSWsEntity confirmotp(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changepin", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Changepin")
    @ResponseWrapper(localName = "changepinResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.ChangepinResponse")
    @Action(input = "http://nayapaybankservice/WebService/changepinRequest", output = "http://nayapaybankservice/WebService/changepinResponse")
    public WalletCMSWsEntity changepin(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ministatementotp", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Ministatementotp")
    @ResponseWrapper(localName = "ministatementotpResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.MinistatementotpResponse")
    @Action(input = "http://nayapaybankservice/WebService/ministatementotpRequest", output = "http://nayapaybankservice/WebService/ministatementotpResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/ministatementotp/Fault/Exception")
    })
    public WalletCMSWsEntity ministatementotp(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceinquiry", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Balanceinquiry")
    @ResponseWrapper(localName = "balanceinquiryResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.BalanceinquiryResponse")
    @Action(input = "http://nayapaybankservice/WebService/balanceinquiryRequest", output = "http://nayapaybankservice/WebService/balanceinquiryResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/balanceinquiry/Fault/Exception")
    })
    public WalletCMSWsEntity balanceinquiry(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "peertopeer", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Peertopeer")
    @ResponseWrapper(localName = "peertopeerResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.PeertopeerResponse")
    @Action(input = "http://nayapaybankservice/WebService/peertopeerRequest", output = "http://nayapaybankservice/WebService/peertopeerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/peertopeer/Fault/Exception")
    })
    public WalletCMSWsEntity peertopeer(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadwallet", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Loadwallet")
    @ResponseWrapper(localName = "loadwalletResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.LoadwalletResponse")
    @Action(input = "http://nayapaybankservice/WebService/loadwalletRequest", output = "http://nayapaybankservice/WebService/loadwalletResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/loadwallet/Fault/Exception")
    })
    public WalletCMSWsEntity loadwallet(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadmerchant", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Loadmerchant")
    @ResponseWrapper(localName = "loadmerchantResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.LoadmerchantResponse")
    @Action(input = "http://nayapaybankservice/WebService/loadmerchantRequest", output = "http://nayapaybankservice/WebService/loadmerchantResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/loadmerchant/Fault/Exception")
    })
    public WalletCMSWsEntity loadmerchant(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns vaulsys.webservice.nayapaybankservice.WalletCMSWsEntity
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unloadmerchant", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.Unloadmerchant")
    @ResponseWrapper(localName = "unloadmerchantResponse", targetNamespace = "http://nayapaybankservice/", className = "vaulsys.webservice.nayapaybankservice.UnloadmerchantResponse")
    @Action(input = "http://nayapaybankservice/WebService/unloadmerchantRequest", output = "http://nayapaybankservice/WebService/unloadmerchantResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://nayapaybankservice/WebService/unloadmerchant/Fault/Exception")
    })
    public WalletCMSWsEntity unloadmerchant(
            @WebParam(name = "arg0", targetNamespace = "")
            WalletCMSWsEntity arg0)
        throws Exception_Exception
    ;

}
