package vaulsys.protocols.ndc.base.TerminalToNetwork.solicited.enums;

import vaulsys.protocols.ndc.base.config.StatusQualifierType;

public class IllegalMessageTypeErrorStatusQualifierType extends StatusQualifierType {
	
	private static final String ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE_VALUE = "01";
	private static final String ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS_VALUE = "02";
	private static final String ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES_VALUE = "03";
	private static final String MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE_VALUE = "04";
	private static final String MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE_VALUE = "05";
	private static final String MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE_VALUE = "06";
	private static final String MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY_VALUE = "10";
	private static final String DOCUMENT_IS_NOT_PRESENT_IN_DPM_VALUE = "11";
	private static final String ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT_VALUE = "12";
	private static final String ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT_VALUE = "13";
	private static final String ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT_VALUE = "14";
	private static final String ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE_VALUE = "15";
	private static final String ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE_VALUE = "17";
	
	
	
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE = new IllegalMessageTypeErrorStatusQualifierType(MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE = new IllegalMessageTypeErrorStatusQualifierType(MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE = new IllegalMessageTypeErrorStatusQualifierType(MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY = new IllegalMessageTypeErrorStatusQualifierType(MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType DOCUMENT_IS_NOT_PRESENT_IN_DPM = new IllegalMessageTypeErrorStatusQualifierType(DOCUMENT_IS_NOT_PRESENT_IN_DPM_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE_VALUE);
	public static final IllegalMessageTypeErrorStatusQualifierType ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE = new IllegalMessageTypeErrorStatusQualifierType(ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE_VALUE);

	
	public IllegalMessageTypeErrorStatusQualifierType(String type) {
		
		super(type);
	}
	
	public static StatusQualifierType getByType(String type) {
		if (ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE_VALUE.equals(type))
			return ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE;
		
		if (ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS_VALUE.equals(type))
			return ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS;
		
		if (ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES_VALUE.equals(type))
			return ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES;
		
		if (MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE_VALUE.equals(type))
			return MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE;
		
		if (MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE_VALUE.equals(type))
			return MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE;
		
		if (MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE_VALUE.equals(type))
			return MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE;
		
		if (MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY_VALUE.equals(type))
			return MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY;
		
		if (DOCUMENT_IS_NOT_PRESENT_IN_DPM_VALUE.equals(type))
			return DOCUMENT_IS_NOT_PRESENT_IN_DPM;
		
		if (ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT_VALUE.equals(type))
			return ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT;
		
		if (ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT_VALUE.equals(type))
			return ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT;
		
		if (ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT_VALUE.equals(type))
			return ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT;
		
		if (ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE_VALUE.equals(type))
			return ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE;
		
		if (ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE_VALUE.equals(type))
			return ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE;
		
		return UNKNOWN;
	}
	
	@Override
	public String getDescription() {
		if (ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE_VALUE.equals(getType()))
			return "ILLEGAL_MESSAGE_RECEIVED_IN_CURRENT_STATE";
		
		if (ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS_VALUE.equals(getType()))
			return "ILLEGAL_MESSAGE_WHILE_DIAGNOSTICS_AND_CLEAR_SOH_ARE_IN_PROGRESS";
		
		if (ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES_VALUE.equals(getType()))
			return "ILLEGAL_MESSAGE_IN_OUT_OF_SEVICE_OR_SUPPLY_MODES";
		
		if (MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE_VALUE.equals(getType()))
			return "MESSAGE_UNACCEPTABLE_IN_CURRENT_MODE";
		
		if (MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE_VALUE.equals(getType()))
			return "MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_NATIVE_MODE";
		
		if (MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE_VALUE.equals(getType()))
			return "MESSAGE_NOT_ALLOWED_WHILE_TERMINAL_CONFIGURED_FOR_DIEBOLD_EMULATION_MODE";
		
		if (MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY_VALUE.equals(getType()))
			return "MESSAGE_NOT_ACCEPTED_WHILE_PROCCESSING_A_TRANSACTION_RREPLY";
		
		if (DOCUMENT_IS_NOT_PRESENT_IN_DPM_VALUE.equals(getType()))
			return "DOCUMENT_IS_NOT_PRESENT_IN_DPM";
		
		if (ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT_VALUE.equals(getType()))
			return "ILLEGAL_PROCESS_WHILE_A_STATEMENT_PRINT_FUNCTION_IS_BEING_CARRIED_OUT";
		
		if (ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT_VALUE.equals(getType()))
			return "ILLEGAL_PRINT_FUNCTION_IN_PROCCESSING_A_DOCUMENT";
		
		if (ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT_VALUE.equals(getType()))
			return "ILLEGAL_DPA_ENVELOPE_DEPOSIT_IN_PROCCESSING_A_DOCUMENT";
		
		if (ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE_VALUE.equals(getType()))
			return "ILLEGAL_EXTENDED_ENCRYPTION_KEY_CHANGE_IN_CARDHOLDER_TRANSACTION_OR_SUSPENDED_MODE";
		
		if (ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE_VALUE.equals(getType()))
			return "ILLEGAL_KEY_CHANGE_IN_RESTRICTED_MODE";
		
		return super.getDescription();	
	}
}
