
package vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-25T18:50:03.663+04:30
 * Generated source version: 2.7.16
 */

@WebFault(name = "BankServiceException", targetNamespace = "http://core.webservice.bank.banking.rahvar.nrdc.com/")
public class BankServiceException_Exception extends Exception {
    
    private vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.BankServiceException bankServiceException;

    public BankServiceException_Exception() {
        super();
    }
    
    public BankServiceException_Exception(String message) {
        super(message);
    }
    
    public BankServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BankServiceException_Exception(String message, vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.BankServiceException bankServiceException) {
        super(message);
        this.bankServiceException = bankServiceException;
    }

    public BankServiceException_Exception(String message, vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.BankServiceException bankServiceException, Throwable cause) {
        super(message, cause);
        this.bankServiceException = bankServiceException;
    }

    public vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.BankServiceException getFaultInfo() {
        return this.bankServiceException;
    }
}
