package vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-25T18:50:03.674+04:30
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "BankEndPointService", 
                  wsdlLocation = "http://192.168.63.10:8001/BankingServices/services/bankservices?wsdl",
                  targetNamespace = "http://core.webservice.bank.banking.rahvar.nrdc.com/") 
public class BankEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://core.webservice.bank.banking.rahvar.nrdc.com/", "BankEndPointService");
    public final static QName BankEndPointPort = new QName("http://core.webservice.bank.banking.rahvar.nrdc.com/", "BankEndPointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.63.10:8001/BankingServices/services/bankservices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankEndPointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.63.10:8001/BankingServices/services/bankservices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankEndPointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankEndPointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BankEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BankServices
     */
    @WebEndpoint(name = "BankEndPointPort")
    public BankServices getBankEndPointPort() {
        return super.getPort(BankEndPointPort, BankServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankServices
     */
    @WebEndpoint(name = "BankEndPointPort")
    public BankServices getBankEndPointPort(WebServiceFeature... features) {
        return super.getPort(BankEndPointPort, BankServices.class, features);
    }

}
