package vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-25T18:50:03.669+04:30
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://core.webservice.bank.banking.rahvar.nrdc.com/", name = "BankServices")
@XmlSeeAlso({ObjectFactory.class, vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.inq.webservice.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BankServices {

    @WebResult(name = "return", targetNamespace = "http://core.webservice.bank.banking.rahvar.nrdc.com/", partName = "return")
    @WebMethod
    public RhvEnfResponse addInfo(
        @WebParam(partName = "RhvEnfRequest", name = "RhvEnfRequest")
        RhvEnfRequest rhvEnfRequest
    ) throws BankServiceException_Exception;
}
