
package vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-25T18:50:03.632+04:30
 * Generated source version: 2.7.16
 * 
 */
public final class BankServices_BankEndPointPort_Client {

    private static final QName SERVICE_NAME = new QName("http://core.webservice.bank.banking.rahvar.nrdc.com/", "BankEndPointService");

    private BankServices_BankEndPointPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankEndPointService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankEndPointService ss = new BankEndPointService(wsdlURL, SERVICE_NAME);
        BankServices port = ss.getBankEndPointPort();  
        
        {
        System.out.println("Invoking addInfo...");
        vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.RhvEnfRequest _addInfo_rhvEnfRequest = null;
        try {
        	vaulsys.webservices.najacxf.com.nrdc.rahvar.banking.bank.webservice.core.RhvEnfResponse _addInfo__return = port.addInfo(_addInfo_rhvEnfRequest);
            System.out.println("addInfo.result=" + _addInfo__return);

        } catch (BankServiceException_Exception e) { 
            System.out.println("Expected exception: BankServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
